version: '3.7'

services:
    # Load balancer
    nginx:
        build: ./nginx
        container_name: nginx_gateway
        restart: always
        links:
            - flask
            - client
        depends_on:
            - flask
            - client
        ports:
            - '5000:80'

    # React client
    client:
        container_name: client
        build: ./front-end
        restart: always
        environment:
            - CI=true
            - NODE_ENV=development
        expose:
            - 3000
        volumes:
            - ./front-end/src:/app/src

    # Flask backend
    flask:
        build: ./flask
        container_name: flask
        restart: always
        links:
            - mongodb
            - redis_queue
        depends_on:
            - mongodb
            - redis_queue
        environment:
            - MONGO_URI=mongodb://mongodb:27017/db
            - REDIS_URI=redis://redis_queue:6379/0
            - GOOGLE_APPLICATION_CREDENTIALS=creds.json
            - MODEL_NAME=sa1model_tf
            - VERSION_NAME=v0_0_0
            - REGION=us-east1
            - GCP_PROJECT=hack-the-north-2021-326503
        expose:
            - 5000
        volumes:
            - ./flask:/app

    # Celery beat scheduler
    beat:
        build: ./flask
        command: ['celery', '-A', 'worker.celery', 'beat', '-l', 'INFO']
        container_name: beat
        restart: always
        links:
            - mongodb
            - redis_queue
        depends_on:
            - mongodb
            - redis_queue
        environment:
            - MONGO_URI=mongodb://mongodb:27017/db
            - REDIS_URI=redis://redis_queue:6379/0
            - GOOGLE_APPLICATION_CREDENTIALS=creds.json
            - MODEL_NAME=sa1model_tf
            - VERSION_NAME=v0_0_0
            - REGION=us-east1
            - GCP_PROJECT=hack-the-north-2021-326503
        volumes:
            - ./flask:/app

    # Celery worker
    worker:
        build: ./flask
        command: ['celery', '-A', 'worker.celery', 'worker', '-l', 'INFO']
        container_name: worker
        restart: always
        links:
            - mongodb
            - redis_queue
        depends_on:
            - mongodb
            - redis_queue
        environment:
            - MONGO_URI=mongodb://mongodb:27017/db
            - REDIS_URI=redis://redis_queue:6379/0
            - GOOGLE_APPLICATION_CREDENTIALS=creds.json
            - MODEL_NAME=sa1model_tf
            - VERSION_NAME=v0_0_0
            - REGION=us-east1
            - GCP_PROJECT=hack-the-north-2021-326503
        volumes:
            - ./flask:/app

    # mongodb
    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        command: mongod
        expose:
            - 27017
        ports:
          - 27017:27017
        logging:
          driver: none

    # Redis message queue
    redis_queue:
        image: redis
        container_name: redis_queue
        restart: always
        expose:
            - 6379
        logging:
          driver: none